# Вопросы

- [ ] Какая связь между классами Throwable, Error, Exception, IOException, RuntimeException?
  - [ ] Что для компилятора означают проверяемые и непроверяемые (checked и unchecked) исключения? Какие из указанных выше исключений к какой категории относятся?
  - [ ] Что логически представляют собой исключения из ветки Error? Можно ли их выбросить самостоятельно? Аналогично расскажите про ветку Exception
  - [ ] Какой класс исключений из упомянутых подходит под определение "ошибки программиста"?
- [ ] Зачем к методу применять оператор throws?
  - [ ] Как он помогает "отсрочить" обработку проверяемых исключений?
  - [ ] Почему не стоит указывать в throws непроверяемые исключения? Объяснить с технической и логической точек зрения
- [ ] Объясните, как вы понимаете следующие правила
  - [ ] "Выбрасывать исключения надо как можно раньше, а обрабатывать как можно позже"
  - [ ] "Методы подкласса не должны выбрасывать более общее исключение, чем методы суперкласса"
- [ ] При объявлении своего исключения нужно два конструктора. Расскажите, что это за конструкторы? Какие параметры они принимают и что происходит у них внутри?
- [ ] Оператор catch
  - [ ] Что делает оператор catch вот в такой форме catch (FileNotFoundException | UnknownHostException ex) { ... ? Почему нельзя так поймать два исключения, если одно является потомком другого?
  - [ ] Почему в catch нужно располагать исключения в порядке, начиная с самого конкретного, а заканчивая самым общим?
- [ ] Для чего у исключений есть методы .initCause(ex) и .getCause()?
- [ ] Расскажите о работе try-catch-**finally** на следующих сценариях:
  - [ ] В try возникло исключение, его обработали в catch
  - [ ] В try возникло исключение, и в catch возникло еще исключение. Доработает ли программа до конца? Если нет, то в каком месте она остановится?
  - [ ] Что будет при исключении в try, если блока catch нет вообще, а есть только finally? А если исключение возникнет и в finally тоже?
    - [ ] Что такое suppressed (подавленные) исключения, которые можно получить из объекта исключения методом .getSuppressed? Как они образуются? Что нужно добавить в сценарий выше, чтобы поймать подавленное исключение?
  - [ ] Какая особенность есть у finally, когда дело касается оператора return? Если return есть и в блоке try, и в блоке finally и при этом не произошло исключений, то какой return сработает?
- [ ] Чем полезен паттерн, когда блок try-finally оборачивается в блок try-catch?
- [ ] Зачем нужен интерфейс AutoClosable с единственным методом .close? Как это связано с техникой "try с ресурсами"?
  - [ ] Как выглядел бы код, аналогичный по эффекту коду try с ресурсами?
  - [ ] В каком порядке выполняется код из .close, catch и finally, если в try с ресурсами возникает исключение? А если исключения не было?
  - [ ] Что если в .close возникает исключение? Как это связанно с suppressed-исключениями? Опишите на сценариях, когда в try есть исключение и когда его там нет



